set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" Keep Plugin commands between vundle#begin/end.
Plugin 'tpope/vim-fugitive'
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

Plugin 'majutsushi/tagbar'
" Plugin 'dracula/vim', { 'name': 'dracula' }
Plugin 'sjl/badwolf'
Plugin 'itchyny/lightline.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'morhetz/gruvbox'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()            " required
filetype plugin indent on    " required

" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

syn on                  " Turn on syntax highlighting

" colorscheme dracula
colorscheme gruvbox
set background=dark     " Setting dark mode

set nocompatible        " Require for Vim coolness
set laststatus=2        " this is to enable the tagline
" set nobk              " Don't create backup files
set ai                  " Turn on auto indentation
set si                  " Turn on smart indent
set ru                  " Turn on the ruler
set sc                  " Show commands
set smarttab            " Turn on smart tabs
set expandtab           " Exapnd tabs to spaces
set tabstop=4           " TAB becomes X spaces
set softtabstop=4       " TAB becomes X spaces in Vim operations
set shiftwidth=4        " Number of spaces for indentation
" set bsdir=last          " Go to last folder when browsing
set hlsearch            " Highlight search results
set incsearch           " Turn on incremental searching
set history=100         " Keep X commands in history
set number              " Turn on line numbers
set t_Co=256            " Enable 256 colors

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }

let g:airline#extensions#tabline#enabled = 1


map <C-n> :NERDTreeToggle<CR>

let g:airline_theme='wombat'