#!/bin/sh
gf aws-keys && echo -e "\n\n"
gf base64 && echo -e "\n\n"
gf cors && echo -e "\n\n"
gf debug-pages && echo -e "\n\n"
gf firebase && echo -e "\n\n"
gf fw && echo -e "\n\n"
gf go-functions && echo -e "\n\n"
gf http-auth && echo -e "\n\n"
gf ip && echo -e "\n\n"
gf json-sec && echo -e "\n\n"
gf meg-headers && echo -e "\n\n"
gf php-curl && echo -e "\n\n"
gf php-errors && echo -e "\n\n"
gf php-serialized && echo -e "\n\n"
gf php-sinks && echo -e "\n\n"
gf php-sources && echo -e "\n\n"
gf s3-buckets && echo -e "\n\n"
gf sec && echo -e "\n\n"
gf servers && echo -e "\n\n"
# gf strings && echo -e "\n\n"
gf takeovers && echo -e "\n\n"
gf upload-fields && echo -e "\n\n"
gf urls | grep -v "https://github.com/tomnomnom/meg"
